### ISSUE TITLE
Faciliter l'indexation du site pour les moteurs de recherche

### ISSUE THREAD

**Issue by stephanie-orrico-grima** [resandco/website-react#27]
Your webpage does not contain any H1 headings. H1 headings help indicate the important topics of your page to search engines. While less important than good meta-titles and descriptions, H1 headings may still help define the topic of your page to search engines.

**Comment by louisremi** [comment]
Les pages comportent bien des H1, mais ton outil d'analyse ne les voit pas. Google les voit bien, mais idéalement il faudrait que les pages soient générées côté serveur et envoyées prêtes à être lues pour faciliter leur indexation (actuellement on envoie les données "en vrac" et les pages sont générées après avoir été téléchargées). 
Je change le titre de l'issue

**Comment by louisremi** [comment]
Les pages comportent bien des H1, mais ton outil d'analyse ne les voit pas. Google les voit bien, mais idéalement il faudrait que les pages soient générées côté serveur et envoyées prêtes à être lues pour faciliter leur indexation (actuellement on envoie les données "en vrac" et les pages sont générées après avoir été téléchargées). 
Je change le titre de l'issue

**Comment by louisremi** [comment]
Issue transférée sur Notion https://www.notion.so/Faciliter-l-indexation-du-site-67479dd0038b435eb7cf214637238d77
