### ISSUE TITLE
Supprimer le bouton "se connecter" sur le blog

### ISSUE THREAD

**Issue by stephanie-orrico-grima** [resandco/website-react#30]
Sur le blog, on peut toujours cliquer sur " se connecter " en haut à gauche. Supprimer cet accès.

**Comment by louisremi** [comment]
Issue transférée https://www.notion.so/Supprimer-le-lien-Se-Connecter-sur-les-pages-du-blog-48764128b93c4639bfa1c91bce21a8ff
