### ISSUE TITLE
Erreur affichage écran

### ISSUE THREAD

**Issue by stephanie-orrico-grima** [resandco/website-react#48]
Lors que l'on est en bas de page et que l'on clique sur un restaurant, le site va directement en bas de page = Navigation pas pratique.
Il faudrait qu'on puisse revenir en haut de page directement

**Comment by louisremi** [comment]
Issue transférée sur Notion https://www.notion.so/Chaque-changement-de-page-doit-ramener-en-haut-de-page-306c560290af41d3b332baa05d81c09b
